export enum EndpointEnum {
  signin = "/v1/users/login/",
  signup = "/v1/users/register/",
  logout = "/users/logout/",
  uploadQuestion = "/v1/ielts-testing/upload-question/",
  getQuestios = "/v1/ielts-testing/get-question/",
  submitAnswer = "/v1/ielts-testing/submit-answer/",
  dummyQuestion = "/ielts-testing/get-dummy-question/",
  dummyEvaluation = "/ielts-testing/get-dummy-evaluation/",
  profile = "/v1/users/profile/",
  badges = "/v1/users/badges/",
  scores = "/v1/users/scores/",
  challenges = "/v1/users/challenges/",
  historicalExams = "/v1/users/historical-exams/",
  historicalExamDetail = "/v1/users/historical-exams/",
}
